services:
  chatapi:
    build:
      context: "./chatapi"
      dockerfile: "Dockerfile"
    container_name: chatapi
    ports:
      - 8000:8000
    networks:
      - chat_network

  flask:
    build:
      context: "./flask"
      dockerfile: "Dockerfile"
    container_name: flask
    ports:
      - 3000:3000
    networks:
      - chat_network
    depends_on:
      - chatapi

networks:
  chat_network:
